configfile: "config/config.yaml"
include: "rules/preprocess.smk"
include: "rules/alignment.smk"
include: "rules/count.smk"
include: "rules/multiqc.smk"

rule all:
    input:
        # QC
        expand(
            "results/fastqc/{sample}_{stage}_fastqc.html",
            sample=config["samples"],
            stage=["raw", "filtered"]
        ),
        expand(
            "results/fastp/{sample}_fastp.html",
            sample=config["samples"]
        ),
        # alignment products
        expand(
            "results/hisat2/{sample}.sorted.bam.bai",
            sample=config["samples"]
        ),
        # counts
        expand(
            "results/counts/{sample}.featureCounts.txt",
            sample=config["samples"]
        ),
        # final MultiQC report
        "results/multiqc/multiqc_report.html"


